#!/bin/bash -ex

VERSION="1.6.0.14"
URL="http://www.prestashop.com/download/old/prestashop_${VERSION}.zip"

[ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
curl -L -f $PROXY "$URL" -o /usr/local/src/prestashop.zip

