#!/bin/bash -ex

VERSION="1.7.6.5"

URL="http://download.prestashop.com/download/releases/prestashop_${VERSION}.zip"

[ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
curl -L -f $PROXY "$URL" -o /usr/local/src/prestashop.zip

