#!/bin/bash -ex

VERSION="8.1.1"

URL="https://github.com/PrestaShop/PrestaShop/releases/download/${VERSION}/prestashop_${VERSION}.zip"

[ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
curl -L -f $PROXY "$URL" -o /usr/local/src/prestashop.zip

