#!/bin/bash -ex

ADMIN_MAIL=admin@example.com
ADMIN_PASS=turnkey1
DOMAIN=www.example.com # set via inithook

DB_NAME=prestashop
DB_USER=prestashop
DB_PASS=$(mcookie)

WEBROOT=/var/www/prestashop

# unpack tarball to webroot and set permissions
unzip -q /usr/local/src/prestashop.zip -d /var/www/
rm -f /usr/local/src/prestashop.zip

chown -R root:root $WEBROOT
chown www-data:www-data $WEBROOT/config
chown www-data:www-data $WEBROOT/upload
chown www-data:www-data $WEBROOT/download
chown www-data:www-data $WEBROOT/sitemap.xml
chown www-data:www-data $WEBROOT/log

chown -R www-data:www-data $WEBROOT/cache
chown -R www-data:www-data $WEBROOT/img
chown -R www-data:www-data $WEBROOT/mails
chown -R www-data:www-data $WEBROOT/modules
chown -R www-data:www-data $WEBROOT/themes/default-bootstrap/lang
chown -R www-data:www-data $WEBROOT/themes/default-bootstrap/cache
chown -R www-data:www-data $WEBROOT/themes/default-bootstrap/pdf/lang
chown -R www-data:www-data $WEBROOT/translations

# convenience execution variables
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

# start mysql server
/etc/init.d/mysql start

# create database
$MYSQL_ADMIN create $DB_NAME

# create database user with privileges on the database
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# update apache configuration
a2dissite 000-default
a2ensite prestashop
a2enmod rewrite

# prestashop installation and configuration
/etc/init.d/apache2 start

php $WEBROOT/install/index_cli.php --timezone="US/Eastern" --domain="$DOMAIN" --db_user="$DB_USER" --db_password="$DB_PASS" --prefix="" --name="TurnKey PrestaShop" --country="us" --firstname="Presta" --lastname="Admin" --password="$ADMIN_PASS" --email="$ADMIN_MAIL" --newsletter=0 --send_email=0

rm -rf $WEBROOT/install
mv $WEBROOT/admin $WEBROOT/administration

# required for friendly urls
touch $WEBROOT/.htaccess
touch $WEBROOT/robots.txt
chown www-data:www-data $WEBROOT/.htaccess
chown www-data:www-data $WEBROOT/robots.txt

# enable ssl
$MYSQL_BATCH --execute "UPDATE $DB_NAME.ps_configuration SET value = '1' WHERE name = 'PS_SSL_ENABLED';"

# stop services
/etc/init.d/apache2 stop
/etc/init.d/mysql stop

