#!/bin/bash -e
# regenerate prestashop secrets

. /etc/default/inithooks

DB_PASS=$(mcookie)
COOKIE_IV=$(mcookie | cut --bytes 1-8)
COOKIE_KEY=$(echo $(mcookie)$(mcookie) | cut --bytes 1-56)

# set default admin password hashed with new cookie
ADMIN_PASS=turnkey1
ADMIN_PASS_HASH=$(echo -n "${COOKIE_KEY}${ADMIN_PASS}" | md5sum | awk '{print $1}')

updateconf() {
    CONF=/var/www/prestashop/config/settings.inc.php
    sed -i "s|'$1', \(.*\)|'$1', '$2');|" $CONF
}

updateconf "_DB_PASSWD_" $DB_PASS
updateconf "_COOKIE_IV_" $COOKIE_IV
updateconf "_COOKIE_KEY_" $COOKIE_KEY

$INITHOOKS_PATH/bin/mysqlconf.py --user=prestashop --pass="$DB_PASS" \
    --query="UPDATE prestashop.employee SET passwd=\"$ADMIN_PASS_HASH\" WHERE id_employee=1;"

