#!/bin/bash -e
# regenerate prestashop secrets

. /etc/default/inithooks

DB_PASS=$(mcookie)
COOKIE_IV=$(mcookie | cut --bytes 1-8)
COOKIE_KEY=$(echo $(mcookie)$(mcookie) | cut --bytes 1-56)

# set default admin password hashed with new cookie
ADMIN_PASS=turnkey1
ADMIN_PASS_HASH=$(echo -n "${COOKIE_KEY}${ADMIN_PASS}" | md5sum | awk '{print $1}')

updateconf() {
    CONF=/var/www/prestashop/app/config/parameters.php
    sed -i "s|'$1' => '\(.*\)'|'$1' => '$2'|" $CONF
}

updateconf "database_password" $DB_PASS
updateconf "cookie_iv" $COOKIE_IV
updateconf "cookie_key" $COOKIE_KEY

$INITHOOKS_PATH/bin/mysqlconf.py --user=prestashop --pass="$DB_PASS" \
    --query="UPDATE prestashop.employee SET passwd=\"$ADMIN_PASS_HASH\" WHERE id_employee=1;"

rm -r /var/www/prestashop/var/cache/*
service apache2 restart
