#!/bin/bash -e
# regenerate prestashop secrets

. /etc/default/inithooks

DB_PASS=$(mcookie)
SECRET=$(mcookie)$(mcookie)
COOKIE_KEY=$(mcookie)$(mcookie)
NEW_COOKIE_KEY=$(php -r \
    'require "/var/www/prestashop/vendor/autoload.php"; echo Defuse\Crypto\Key::createNewRandomKey()->saveToAsciiSafeString();')

# Set the disposable build-time administrator password before the normal
# firstboot hook applies the user-provided password.
ADMIN_PASS=turnkey1

updateconf() {
    CONF=/var/www/prestashop/app/config/parameters.php
    sed -E -i "s|('$1'[[:space:]]*=>[[:space:]]*)[^,]*,|\1'$2',|" "$CONF"
    grep -Eq "'$1'[[:space:]]*=>[[:space:]]*'$2'," "$CONF"
}

updateconf "database_password" $DB_PASS
updateconf "secret" $SECRET
updateconf "cookie_key" $COOKIE_KEY
updateconf "new_cookie_key" $NEW_COOKIE_KEY

ADMIN_PASS_HASH=$(php -r 'echo password_hash($argv[1], PASSWORD_BCRYPT);' -- "$ADMIN_PASS")
$INITHOOKS_PATH/bin/mysqlconf.py --user=prestashop --pass="$DB_PASS" \
    --query="UPDATE prestashop.employee SET passwd=\"$ADMIN_PASS_HASH\" WHERE id_employee=1;"

find /var/www/prestashop/var/cache -mindepth 1 -delete
service apache2 restart
