#!/bin/bash -e
# set prestashop admin password and email

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/prestashop.py --pass="$APP_PASS" --email="$APP_EMAIL"

